// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: beer.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "beer";

export interface GetBeersRequest {
}

export interface GetBeersByIdsRequest {
  ids: number[];
}

export interface Beer {
  id: number;
  name: string;
  bartender_preparation_time: number;
  volume: number;
  pour_time: number;
}

export interface GetBeersResponse {
  beers: Beer[];
}

function createBaseGetBeersRequest(): GetBeersRequest {
  return {};
}

export const GetBeersRequest: MessageFns<GetBeersRequest> = {
  encode(_: GetBeersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBeersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBeersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetBeersRequest {
    return {};
  },

  toJSON(_: GetBeersRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBeersRequest>, I>>(base?: I): GetBeersRequest {
    return GetBeersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBeersRequest>, I>>(_: I): GetBeersRequest {
    const message = createBaseGetBeersRequest();
    return message;
  },
};

function createBaseGetBeersByIdsRequest(): GetBeersByIdsRequest {
  return { ids: [] };
}

export const GetBeersByIdsRequest: MessageFns<GetBeersByIdsRequest> = {
  encode(message: GetBeersByIdsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.ids) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBeersByIdsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBeersByIdsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.ids.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ids.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBeersByIdsRequest {
    return { ids: globalThis.Array.isArray(object?.ids) ? object.ids.map((e: any) => globalThis.Number(e)) : [] };
  },

  toJSON(message: GetBeersByIdsRequest): unknown {
    const obj: any = {};
    if (message.ids?.length) {
      obj.ids = message.ids.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBeersByIdsRequest>, I>>(base?: I): GetBeersByIdsRequest {
    return GetBeersByIdsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBeersByIdsRequest>, I>>(object: I): GetBeersByIdsRequest {
    const message = createBaseGetBeersByIdsRequest();
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseBeer(): Beer {
  return { id: 0, name: "", bartender_preparation_time: 0, volume: 0, pour_time: 0 };
}

export const Beer: MessageFns<Beer> = {
  encode(message: Beer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.bartender_preparation_time !== 0) {
      writer.uint32(24).int32(message.bartender_preparation_time);
    }
    if (message.volume !== 0) {
      writer.uint32(32).int32(message.volume);
    }
    if (message.pour_time !== 0) {
      writer.uint32(40).int32(message.pour_time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Beer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBeer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.bartender_preparation_time = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.volume = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.pour_time = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Beer {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      bartender_preparation_time: isSet(object.bartenderPreparationTime)
        ? globalThis.Number(object.bartenderPreparationTime)
        : isSet(object.bartender_preparation_time)
        ? globalThis.Number(object.bartender_preparation_time)
        : 0,
      volume: isSet(object.volume) ? globalThis.Number(object.volume) : 0,
      pour_time: isSet(object.pourTime)
        ? globalThis.Number(object.pourTime)
        : isSet(object.pour_time)
        ? globalThis.Number(object.pour_time)
        : 0,
    };
  },

  toJSON(message: Beer): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.bartender_preparation_time !== 0) {
      obj.bartenderPreparationTime = Math.round(message.bartender_preparation_time);
    }
    if (message.volume !== 0) {
      obj.volume = Math.round(message.volume);
    }
    if (message.pour_time !== 0) {
      obj.pourTime = Math.round(message.pour_time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Beer>, I>>(base?: I): Beer {
    return Beer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Beer>, I>>(object: I): Beer {
    const message = createBaseBeer();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.bartender_preparation_time = object.bartender_preparation_time ?? 0;
    message.volume = object.volume ?? 0;
    message.pour_time = object.pour_time ?? 0;
    return message;
  },
};

function createBaseGetBeersResponse(): GetBeersResponse {
  return { beers: [] };
}

export const GetBeersResponse: MessageFns<GetBeersResponse> = {
  encode(message: GetBeersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.beers) {
      Beer.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBeersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBeersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.beers.push(Beer.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBeersResponse {
    return { beers: globalThis.Array.isArray(object?.beers) ? object.beers.map((e: any) => Beer.fromJSON(e)) : [] };
  },

  toJSON(message: GetBeersResponse): unknown {
    const obj: any = {};
    if (message.beers?.length) {
      obj.beers = message.beers.map((e) => Beer.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBeersResponse>, I>>(base?: I): GetBeersResponse {
    return GetBeersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBeersResponse>, I>>(object: I): GetBeersResponse {
    const message = createBaseGetBeersResponse();
    message.beers = object.beers?.map((e) => Beer.fromPartial(e)) || [];
    return message;
  },
};

export type BeerServiceService = typeof BeerServiceService;
export const BeerServiceService = {
  getBeers: {
    path: "/beer.BeerService/GetBeers" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetBeersRequest): Buffer => Buffer.from(GetBeersRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetBeersRequest => GetBeersRequest.decode(value),
    responseSerialize: (value: GetBeersResponse): Buffer => Buffer.from(GetBeersResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetBeersResponse => GetBeersResponse.decode(value),
  },
  getBeersByIds: {
    path: "/beer.BeerService/GetBeersByIds" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetBeersByIdsRequest): Buffer => Buffer.from(GetBeersByIdsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetBeersByIdsRequest => GetBeersByIdsRequest.decode(value),
    responseSerialize: (value: GetBeersResponse): Buffer => Buffer.from(GetBeersResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetBeersResponse => GetBeersResponse.decode(value),
  },
} as const;

export interface BeerServiceServer extends UntypedServiceImplementation {
  getBeers: handleUnaryCall<GetBeersRequest, GetBeersResponse>;
  getBeersByIds: handleUnaryCall<GetBeersByIdsRequest, GetBeersResponse>;
}

export interface BeerServiceClient extends Client {
  getBeers(
    request: GetBeersRequest,
    callback: (error: ServiceError | null, response: GetBeersResponse) => void,
  ): ClientUnaryCall;
  getBeers(
    request: GetBeersRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetBeersResponse) => void,
  ): ClientUnaryCall;
  getBeers(
    request: GetBeersRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetBeersResponse) => void,
  ): ClientUnaryCall;
  getBeersByIds(
    request: GetBeersByIdsRequest,
    callback: (error: ServiceError | null, response: GetBeersResponse) => void,
  ): ClientUnaryCall;
  getBeersByIds(
    request: GetBeersByIdsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetBeersResponse) => void,
  ): ClientUnaryCall;
  getBeersByIds(
    request: GetBeersByIdsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetBeersResponse) => void,
  ): ClientUnaryCall;
}

export const BeerServiceClient = makeGenericClientConstructor(BeerServiceService, "beer.BeerService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): BeerServiceClient;
  service: typeof BeerServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
